site_name: GO-CAM Reviews
site_description: AI generated reviews of GO-CAMs

theme:
  name: material
  palette:
    primary: indigo
    accent: indigo
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.expand
    - navigation.indexes
    - toc.follow
    - content.code.copy
  font:
    text: Roboto
    code: Roboto Mono
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.highlight
  - pymdownx.tabbed
  - attr_list
  - tables
  - toc:
      permalink: true

plugins:
  - search
  - mermaid2:
      version: 10.9.0
  - awesome-pages      

nav:
  - Home: index.md
  - Summaries:
      - Overall: summaries/overall.md
      - Adapters: summaries/summary-adapters.md
      - Carriers: summaries/summary-carriers.md
  - Reviews:
      - ...
